name: Bug 报告
description: 在提出问题前请先升级到最新客户端，同时也请通过搜索确认是否有人提出过相同问题。
title: "[Bug]: "
labels: ["bug"]
body:
  - type: input
    id: "expectation"
    attributes:
      label: "预期情况"
      description: "描述你认为应该发生什么"
    validations:
      required: true
  - type: textarea
    id: "describe-the-bug"
    attributes:
      label: "实际情况"
      description: "描述实际发生了什么"
    validations:
      required: true
  - type: textarea
    id: "reproduction-method"
    attributes:
      label: "复现方法"
      description: "在BUG出现前执行了哪些操作"
      placeholder: 标序号
    validations:
      required: true
  - type: textarea
    id: "more"
    attributes:
      label: "额外信息"
      description: "可选"
    validations:
      required: false
  - type: checkboxes
    id: "latest-version"
    attributes:
      label: "我确认已更新至最新版本"
      options:
        - label: 是
          required: true
  - type: checkboxes
    id: "issues"
    attributes:
      label: "我确认已查询历史issues"
      options:
        - label: 是
          required: true
