name: ✨ 新功能提案 ✨
description: "💡 有什么好点子吗？快来分享你的创意吧～"
title: "[✨功能提案]: "
labels: ['enhancement']
body:
  - type: input
    id: problem
    attributes:
      label: 🌈 你想要的功能  
      description: "简单描述一下你希望增加或改进的功能吧～让我们一起让软件变得更棒！"  
    validations:
      required: false
  - type: textarea
    id: way-to-solve
    attributes:
      label: 🚀 理想中的解决方案  
      description: "你心目中的完美方案是怎样的呢？尽情发挥想象力，不用担心技术细节哦～"  
    validations:
      required: true
  - type: textarea
    id: instead
    attributes:
      label: 🤔 其他可能的解决方案（可选）  
      description: "如果你想到了其他点子，也可以在这里和我们分享哦～多多益善！"  
    validations:
      required: false
  - type: checkboxes
    id: "latest-version"
    attributes:
      label: "✅ 最后一步"
      description: "在提交你的绝妙想法前，请确认以下事项～"  
      options:
        - label: "🌟 我已经仔细看过最新版本，确认我想要的功能还没有实现～"
          required: true
        - label: "📋 我已经翻阅过现有的功能请求，确认没有撞车哦～"
          required: true
