name: 功能请求
description: "💡 你有好的想法？来这里提建议吧！"
title: "[Feature request]: "
labels: ['enhancement']
body:
  - type: input
    id: problem
    attributes:
      label: 遇到的问题  
      description: "请简单描述一下你遇到的问题或需要改进的地方"  
      placeholder: "例如：在使用过程中遇到的具体问题或不足"  
    validations:
      required: true
  - type: textarea
    id: way-to-solve
    attributes:
      label: 你希望的解决方案  
      description: "理想情况下，你希望软件怎么做呢？欢迎畅所欲言！"  
    validations:
      required: true
  - type: textarea
    id: instead
    attributes:
      label: 你考虑过的其他方案（可选）  
      description: "如果有其他替代方案，也可以写在这里哦～"  
    validations:
      required: false
