name: build catime

on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'README_EN.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'README.md'
      - 'README_EN.md'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v3
      
    - name: 设置中国时区
      run: |
        sudo timedatectl set-timezone Asia/Shanghai
        echo "当前时区: $(date +%Z)"
        echo "当前时间: $(date)"
        
    - name: 安装MinGW编译器
      run: |
        sudo apt-get update
        sudo apt-get install -y mingw-w64
        
    - name: 安装XMake
      run: |
        bash <(curl -fsSL https://xmake.io/shget.text)
        source ~/.xmake/profile
        xmake --version
        
    - name: 提取版本号
      id: get_version
      run: |
        VERSION=$(grep -oP '#define CATIME_VERSION "\K[^"]+' resource/resource.h)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "版本号: $VERSION"
      
    - name: 编译应用程序
      run: |
        # 创建输出目录
        mkdir -p output
        # 执行xmake构建
        xmake -y
        # 查找构建产物并复制到输出目录
        find . -name "catime.exe" -type f -print -exec cp {} output/ \;
        echo "使用xmake完成构建"
        
    - name: 添加版本信息文件
      run: |
        echo "# Catime ${{ env.VERSION }} 版本说明" > output/README.txt
        echo "感谢您使用 catime_${{ env.VERSION }} 测试版！" >> output/README.txt
        echo "" >> output/README.txt
        echo "## 版本信息" >> output/README.txt
        echo "- 版本号：${{ env.VERSION }}" >> output/README.txt
        echo "- 版本类型：测试版" >> output/README.txt
        echo "- 构建日期：$(date '+%Y-%m-%d %H:%M:%S') (UTC+8)" >> output/README.txt
        echo "- 构建编号：${GITHUB_RUN_NUMBER:-未知}" >> output/README.txt
        echo "" >> output/README.txt
        echo "## 重要提示" >> output/README.txt
        echo "本版本为测试版本，可能存在功能不稳定或界面布局调整等情况。" >> output/README.txt
        echo "如遇到问题，请通过 Issues 页面向我们反馈。您的意见将帮助我们改进产品质量。" >> output/README.txt
        echo "" >> output/README.txt
        echo "-----------------------------------" >> output/README.txt
        echo "" >> output/README.txt
        echo "# catime_${{ env.VERSION }} Version Information" >> output/README.txt
        echo "Thank you for using Catime ${{ env.VERSION }} Beta version!" >> output/README.txt
        echo "" >> output/README.txt
        echo "## Version Information" >> output/README.txt
        echo "- Version: ${{ env.VERSION }}" >> output/README.txt
        echo "- Version Type: Beta" >> output/README.txt
        echo "- Build Date: $(date '+%Y-%m-%d %H:%M:%S') (UTC+8)" >> output/README.txt
        echo "- Build Number: ${GITHUB_RUN_NUMBER:-Unknown}" >> output/README.txt
        echo "" >> output/README.txt
        echo "## Important Notes" >> output/README.txt
        echo "This is a beta version, which may have unstable features or UI layout adjustments." >> output/README.txt
        echo "If you encounter any issues, please provide feedback through the Issues page. Your opinions will help us improve product quality." >> output/README.txt   
    - name: 重命名为测试版
      run: |
        mv output/catime.exe output/catime_${{ env.VERSION }}_${{ github.run_number }}.exe
        
    - name: 创建发布包
      run: |
        mkdir -p release
        cp output/catime_${{ env.VERSION }}_${{ github.run_number }}.exe release/
        cp output/README.txt release/
        cd release
        zip -r catime_${{ env.VERSION }}_${{ github.run_number }}.zip *
        mv catime_${{ env.VERSION }}_${{ github.run_number }}.zip ../output/
        
    - name: 上传构建结果
      uses: actions/upload-artifact@v4
      with:
        name: catime-windows-${{ env.VERSION }}-${{ github.run_number }}
        path: |
          output/catime_${{ env.VERSION }}_${{ github.run_number }}.exe
          output/README.txt
        # 注意：构建完成后，您可以在GitHub Actions工作流运行页面的"Artifacts"部分下载构件
